from __future__ import annotations

import os
import json
import requests


# -------------------------
# Función principal
# -------------------------
def post_comment(report_path: str = "reports/output.json"):
    token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPOSITORY")
    pr_number = os.getenv("PR_NUMBER")

    if not token or not repo or not pr_number:
        print("Missing GitHub context - skipping PR comment")
        return

    if not os.path.exists(report_path):
        print("Report file not found - skipping PR comment")
        return

    with open(report_path) as f:
        data = json.load(f)

    message = build_summary(data)

    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json"
    }

    response = requests.post(url, headers=headers, json={"body": message})

    if response.status_code >= 300:
        print("Failed to post comment:", response.text)
    else:
        print("PR comment posted successfully")


# -------------------------
# Construcción del mensaje
# -------------------------
def build_summary(data: list[dict]) -> str:
    fail = []
    review = []

    for entry in data:
        status = entry.get("final_status")
        method = entry.get("method")
        reason = extract_reason(entry)

        if status == "FAIL":
            fail.append({"method": method, "reason": reason})
        elif status == "NEEDS REVIEW":
            review.append({"method": method, "reason": reason})

    message = "##AutoDoc Results\n\n"

    if not fail and not review:
        message += "All methods are consistent.\n"
        message += "\n---\n_Generated by AutoDoc_"
        return message

    # -------------------------
    # FAIL
    # -------------------------
    if fail:
        message += "**FAIL (blocking issues):**\n\n"
        for f in fail:
            message += f"- `{f['method']}` → {f['reason']}\n"

    # -------------------------
    # NEEDS REVIEW
    # -------------------------
    if review:
        message += "\n**NEEDS REVIEW:**\n\n"
        for r in review:
            message += f"- `{r['method']}` → {r['reason']}\n"

    message += "\n---\n"
    message += "_Generated by AutoDoc_"

    return message


# -------------------------
# Extracción de razón
# -------------------------
def extract_reason(entry: dict) -> str:
    details = entry.get("details", {})

    # 1. Prioridad: IA
    ai = details.get("ai_evaluation")
    if ai:
        explanation = ai.get("explanation")
        if explanation:
            return explanation.strip()

    # 2. Fallback: reglas
    rules = details.get("rules_evaluation", {})
    issues = rules.get("issues", [])

    if issues:
        first_issue = issues[0]
        return first_issue.get("message", "Rule violation")

    # 3. Default
    return "No details available"