from __future__ import annotations

import os
import json
import requests


# -------------------------
# Función principal
# -------------------------
def post_comment(report_path: str = "reports/output.json"):
    token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPOSITORY")
    pr_number = os.getenv("PR_NUMBER")

    if not token or not repo or not pr_number:
        print("Missing GitHub context - skipping PR comment")
        return

    if not os.path.exists(report_path):
        print("Report file not found - skipping PR comment")
        return

    with open(report_path) as f:
        data = json.load(f)

    message = build_summary(data)

    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json"
    }

    response = requests.post(url, headers=headers, json={"body": message})

    if response.status_code >= 300:
        print("Failed to post comment:", response.text)
    else:
        print("PR comment posted successfully")


# -------------------------
# Construcción del mensaje
# -------------------------
def build_summary(data: list[dict]) -> str:
    fail = []
    review = []

    for entry in data:
        status = entry.get("final_status")

        if status == "FAIL":
            fail.append(entry)
        elif status == "NEEDS REVIEW":
            review.append(entry)

    message = "##AutoDoc Results\n\n"

    if not fail and not review:
        message += "All methods are consistent.\n"
        message += "\n---\n_Generated by AutoDoc_"
        return message

    # -------------------------
    # FAIL
    # -------------------------
    if fail:
        message += "**FAIL (blocking issues):**\n\n"
        for entry in fail:
            message += format_method(entry) + "\n\n"

    # -------------------------
    # NEEDS REVIEW
    # -------------------------
    if review:
        message += "\n**NEEDS REVIEW:**\n\n"
        for entry in review:
            message += format_method(entry) + "\n\n"

    message += "\n---\n"
    message += "_Generated by AutoDoc_"

    return message


# -------------------------
# Formateo por método
# -------------------------
def format_method(entry: dict) -> str:
    method_data = entry.get("method", {})
    jd = method_data.get("javadoc", {})

    name = method_data.get("method_name", "unknown")
    description = jd.get("description", "")
    reason = extract_reason(entry)

    result = f"- `{name}`"

    if description:
        result += f"\n  ↳ Descripción: \"{description}\""

    result += f"\n  ↳ Problema: {reason}"

    return result


# -------------------------
# Extracción de razón
# -------------------------
def extract_reason(entry: dict) -> str:
    details = entry.get("details", {})

    # 1. Prioridad: campo directo "reason"
    reason = details.get("reason")
    if reason:
        return reason.strip()

    # 2. Explicación interna (estructura actual)
    nested = details.get("details", {})
    explanation = nested.get("explanation")
    if explanation:
        return explanation.strip()

    # 3. Resultado IA fallback
    result = nested.get("result")
    if result == "CONSISTENT":
        return "Consistent according to AI"
    if result == "INCONSISTENT":
        return "Inconsistency detected"
    if result == "UNCERTAIN":
        return "AI could not determine consistency"

    # 4. Rules fallback
    rules = details.get("rules_evaluation", {})
    issues = rules.get("issues", [])

    if issues:
        return issues[0].get("message", "Rule violation")

    # 5. Default
    return "No explicit reason provided by analysis"