from __future__ import annotations

import os
import json
import requests


def post_comment(report_path: str = "reports/output.json"):
    token = os.getenv("GITHUB_TOKEN")
    repo = os.getenv("GITHUB_REPOSITORY")
    pr_number = os.getenv("PR_NUMBER")

    if not token or not repo or not pr_number:
        print("Missing GitHub context - skipping PR comment")
        return

    with open(report_path) as f:
        data = json.load(f)

    summary = build_summary(data)

    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"

    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json"
    }

    response = requests.post(url, headers=headers, json={"body": summary})

    if response.status_code >= 300:
        print("Failed to post comment:", response.text)
    else:
        print("PR comment posted successfully")


def build_summary(data: list[dict]) -> str:
    fail = []
    review = []

    for r in data:
        if r["final_status"] == "FAIL":
            fail.append(r["method"])
        elif r["final_status"] == "NEEDS REVIEW":
            review.append(r["method"])

    message = "## 📊 AutoDoc Results\n\n"

    if not fail and not review:
        message += "✅ All methods are consistent.\n"
        return message

    if fail:
        message += "**FAIL (blocking issues):**\n"
        for m in fail:
            message += f"- {m}\n"

    if review:
        message += "\n**NEEDS REVIEW:**\n"
        for m in review:
            message += f"- {m}\n"

    message += "\n---\n"
    message += "_Generated by AutoDoc_"

    return message