name: AutoDoc Reusable Workflow

on:
  workflow_call:
    inputs:
      override:
        description: "Override NEEDS REVIEW (true/false)"
        required: false
        type: string
        default: "false"
    secrets:
      GEMINI_API_KEY:
        required: true

jobs:
  autodoc:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    outputs:
      report-path: reports/output.json

    steps:
      #Checkout del repo cliente (donde corre el PR)
      - name: Checkout target repository
        uses: actions/checkout@v4

      #Checkout del repo AutoDoc (herramienta)
      - name: Checkout AutoDoc source
        uses: actions/checkout@v4
        with:
          repository: emaafe/autodoc
          path: autodoc

      #Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      #Instalar dependencias de AutoDoc
      - name: Install dependencies
        run: pip install -r autodoc/requirements.txt

      #Ejecutar AutoDoc
      - name: Run AutoDoc
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AUTODOC_OVERRIDE: ${{ inputs.override }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: python autodoc/analyzer/main.py

      #Guardar JSON
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: autodoc-report
          path: reports/output.json

      #Guardar PDF
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: autodoc-pdf
          path: reports/output.pdf


  blocking-check:
    runs-on: ubuntu-latest
    needs: autodoc

    steps:
      - name: Checkout AutoDoc source
        uses: actions/checkout@v4
        with:
          repository: emaafe/autodoc
          path: autodoc

      - name: Download report
        uses: actions/download-artifact@v4
        with:
          name: autodoc-report
          path: reports/

      - name: Run blocking check
        run: python -m autodoc.analyzer.check_blocking


  review-check:
    runs-on: ubuntu-latest
    needs: autodoc

    steps:
      - name: Checkout AutoDoc source
        uses: actions/checkout@v4
        with:
          repository: emaafe/autodoc
          path: autodoc

      - name: Download report
        uses: actions/download-artifact@v4
        with:
          name: autodoc-report
          path: reports/

      - name: Run review check
        env:
          AUTODOC_OVERRIDE: ${{ inputs.override }}
        run: python -m autodoc.analyzer.check_review